### ISSUE TITLE
Errors due to name mismatch in package names

### ISSUE THREAD

**Issue by harshasridhar** [ververica/flink-training-exercises#37]
In the following files, the package names have "datastream_scala" instead of "datastream_java" causing errors, changing which the errors are resolved.
Couldn't make a branch and push changes due to lack of permission to do so.

src/test/java/com/dataartisans/flinktraining/exercises/datastream_java/basics/RideCleansingScalaTest.java
src/test/java/com/dataartisans/flinktraining/exercises/datastream_java/process/ExpiringStateScalaTest.java
src/test/java/com/dataartisans/flinktraining/exercises/datastream_java/process/LongRidesScalaTest.java
src/test/java/com/dataartisans/flinktraining/exercises/datastream_java/state/RidesAndFaresScalaTest.java
src/test/java/com/dataartisans/flinktraining/exercises/datastream_java/windows/HourlyTipsScalaTest.java
src/test/java/com/dataartisans/flinktraining/exercises/datastream_java/windows/PopularPlacesScalaTest.java

**Comment by alpinegizmo** [comment]
Pull requests are welcome; that's the way to propose fixes and improvements.

However, everything builds cleanly as is. These tests are meant to import the datastream_scala packages, as their purpose is to test the scala exercises and solutions.

Note that working with these exercises in IntelliJ requires installing the Scala Plugin and adding a Scala SDK to the project structure. See the section "3. Import the flink-training-exercises project into your IDE" at https://training.ververica.com/devEnvSetup.html.
