### ISSUE TITLE
Dataset links are broken

### ISSUE THREAD

**Issue by hyiger** [ververica/flink-training-exercises#49]
No longer able to download the datasets for the training-exercises the links are broken:

`
wget http://training.ververica.com/trainingData/nycTaxiRides.gz                      
URL transformed to HTTPS due to an HSTS policy
--2020-06-29 15:19:37--  https://training.ververica.com/trainingData/nycTaxiRides.gz
Resolving training.ververica.com (training.ververica.com)... 151.101.65.195, 151.101.1.195
Connecting to training.ververica.com (training.ververica.com)|151.101.65.195|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-06-29 15:19:37 ERROR 404: Not Found.
`

**Comment by alpinegizmo** [comment]
Thanks for pointing this out! Fixed.

**Comment by Lswx2017** [comment]
The link broken again!
